import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Board Game Score Keeper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} prose grid min-h-screen grid-cols-1 grid-rows-[auto_1fr_auto] items-center justify-between`}
      >
        <Header />

        <main className="h-full px-6">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
